### ISSUE TITLE
Sovrascrittura di template a runtime

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/adriaclim-geoportal#1]
Il metodo `listAllDatasets` scrive il template `AdriaProject/templates/allDatasets.html` (https://github.com/ARPA-SIMC/adriaclim-geoportal/blob/main/adriaclim-master/AdriaApp1/code/AdriaProject/myFunctions/allFunctions.py#L437). Stessa cosa mi pare succeda per `AdriaProject/templates/getData.html` (https://github.com/ARPA-SIMC/adriaclim-geoportal/blob/main/adriaclim-master/AdriaApp1/code/AdriaProject/myFunctions/allFunctions.py#L461).

Questo potrebbe creare due problemi:

1. Il codice potrebbe essere in un'area readonly e quindi non scrivibile.
2. Il metodo è invocato in una view (https://github.com/ARPA-SIMC/adriaclim-geoportal/blob/6571b008d1834b3effc7605b2491d0c69665951d/adriaclim-master/AdriaApp1/code/AdriaProject/Dataset/views.py#L97) e quindi ci potrebbero essere scritture contemporanee.

Probabilmente, conviene rendere l'output della chiamata al server ERDDAP un parametro da passare al rendering insieme al template.

**Comment by edigiacomo** [comment]
@fraFerrari99 la issue è risolta? Si può chiudere?

**Comment by fraFerrari99** [comment]
Sisi scusami, ora chiudo quelle risolte!
