### ISSUE TITLE
Django runserver should not be used in production

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/adriaclim-geoportal#15]
`manage.py runserver` is a development web server and should not be used in production. See https://docs.djangoproject.com/en/4.1/howto/deployment/ for alternatives (ASGI o WSGI).

https://github.com/ARPA-SIMC/adriaclim-geoportal/blob/83d251ab3f46c655d8b64883755c5f0c5023fa61/adriaclim-master/AdriaApp1/docker-compose.yml#L12

**Comment by fraFerrari99** [comment]
Hi Emanuele, I deployed the project with ASGI using hypercorn, so I think this problem is solved. Thanks for opening the issue advising the mistake!
