### ISSUE TITLE
SECRET_KEY must be a large random value and it must be kept secret

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/adriaclim-geoportal#17]
See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/#secret-key

**Comment by fraFerrari99** [comment]
I changed the value of SECRET_KEY and kept it secret, in fact as you can see it is not present in the settings.py file and I did this using the dotenv library with `load_dotenv(find_dotenv())` and then `os.environ["SECRET_KEY"]`.
