### ISSUE TITLE
Database credentials must be kept secret 

### ISSUE THREAD

**Issue by edigiacomo** [ARPA-SIMC/adriaclim-geoportal#18]
See `docker-compose.yml`.

**Comment by fraFerrari99** [comment]
I did it putting all the db credentials in an .env file that is put in .gitignore file and then I passed them in the docker_compose.yml file using $POSTGRES_NAME, $POSTGRES_USER and  $POSTGRES_PASSWORD. I hope this is the best way to solve this problem!
