### ISSUE TITLE
DEBUG = False ==> Static Files not found

### ISSUE THREAD

**Issue by fraFerrari99** [ARPA-SIMC/adriaclim-geoportal#21]
Ciao Emanuele,

il nuovo collega si è scaricato l’ultima versione del progetto ma, quando ha provato a lanciarlo, ha incontrato tutta una serie di errori legati ai file nella cartella static e si trattava, per ogni file in questa cartella, di un errore di tipo MIME e cioè: 

Django refused to apply style because its MIME Type (‘text/html’) is not a supported stylesheet MIME type.
 
Abbiamo provato in vari modi a risolvere questo problema (usando la libreria mimetype, installando whitenoise ecc.) ma purtroppo il problema non è stato risolto ma lo è stato, solo momentaneamente ovviamente, mettendo DEBUG = True che in fase di produzione ovviamente non va fatto.

Che tipo di problema può esserci? Qualcosa legato al file settings.py e in particolare a questa parte di codice?

```
STATIC_URL = '/static/'
STATIC_ROOT=os.path.join(BASE_DIR,'static_root/')

STATICFILES_DIRS=[
    BASE_DIR / 'static',
]
```

**Comment by edigiacomo** [comment]
In fase di sviluppo - dove generalmente è comodo e utile usare `DEBUG = True` - Django permette di servire i file statici mediante l'uso di `runserver` (riferimento: https://docs.djangoproject.com/en/4.1/howto/static-files/)

In produzione - dove invece è necessario usare `DEBUG = False` - si deve fare il deploy dei file statici (riferimento https://docs.djangoproject.com/en/4.1/howto/static-files/deployment/).

In generale, la documentazione ufficiale di Django https://docs.djangoproject.com/ è fatta molto bene e trovi più o meno tutto quello che ti serve.

**Comment by fraFerrari99** [comment]
Ciao Emanuele,

alla fine sono riuscito a risolvere il problema andando a creare in Docker un altro container specifico per Nginx in cui vengono salvati tutti i file statici e ora tutto funziona correttamente.

Grazie mille per i consigli!
