### ISSUE TITLE
Georeferenced polygons in the geoportal

### ISSUE THREAD

**Issue by dcesari** [ARPA-SIMC/adriaclim-geoportal#9]
Come emerso dalla conferenza c'è l'esigenza di avere diverse gerarchie di aree poligonali da mostrare sulla mappa e utilizzare per l'aggregazione spaziale degli indicatori.

Propongo che il geoportale metta a disposizione una vista con una singola area che copre  l'Adriatico e la parte di terraferma i cui fiumi scolano nell'Adriatico, diciamo un rettangolo lon 6.5-22.0 lat 38.5-47.0, e una seconda vista, che sarebbe la vista di default all'apertura, con le 8 "pilot areas" del progetto, piò o meno queste:
![pilot](https://user-images.githubusercontent.com/681382/172811662-72d51b48-407d-4284-8e5b-ddf27033b972.png)

Mi posso procurare una mappa migliore se è il caso, ma non è fondmantale che le aree siano esatte.
Poi c'è l'esigenza di avere una vista sui comuni, questa la lascerei come opzione all'utente (quando ci sarà autenticazione), cioè di caricare un geojson personale con i poligoni di sua scelta.

Quindi da qualche parte nell'interfaccia ci dovrebbe essere un selettore che commuta tra le viste Adriatico|Pilot|una o più custom area. Le aree visualizzate saranno poi quelle su cui si basa la selezione dei punti per la visualizzazione degli indicatori.

**Comment by fraFerrari99** [comment]
Direi che sono state realizzate tutte le cose richieste ma lascio l'issue aperta per possibili futuri sviluppi.
